//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArticlesClient.ArticlesService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArticleData", Namespace="http://schemas.datacontract.org/2004/07/Articles.Services.Models")]
    [System.SerializableAttribute()]
    public partial class ArticleData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArticlesClient.ArticlesService.CommentData[] CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArticlesClient.ArticlesService.CommentData[] Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommentData", Namespace="http://schemas.datacontract.org/2004/07/Articles.Services.Models")]
    [System.SerializableAttribute()]
    public partial class CommentData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ArticleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ArticleId {
            get {
                return this.ArticleIdField;
            }
            set {
                if ((this.ArticleIdField.Equals(value) != true)) {
                    this.ArticleIdField = value;
                    this.RaisePropertyChanged("ArticleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ArticlesService.IArticlesService")]
    public interface IArticlesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticlesService/GetAll", ReplyAction="http://tempuri.org/IArticlesService/GetAllResponse")]
        ArticlesClient.ArticlesService.ArticleData[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticlesService/GetAll", ReplyAction="http://tempuri.org/IArticlesService/GetAllResponse")]
        System.Threading.Tasks.Task<ArticlesClient.ArticlesService.ArticleData[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticlesService/Get", ReplyAction="http://tempuri.org/IArticlesService/GetResponse")]
        ArticlesClient.ArticlesService.ArticleData Get(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticlesService/Get", ReplyAction="http://tempuri.org/IArticlesService/GetResponse")]
        System.Threading.Tasks.Task<ArticlesClient.ArticlesService.ArticleData> GetAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticlesService/Create", ReplyAction="http://tempuri.org/IArticlesService/CreateResponse")]
        System.Nullable<long> Create(ArticlesClient.ArticlesService.ArticleData article);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticlesService/Create", ReplyAction="http://tempuri.org/IArticlesService/CreateResponse")]
        System.Threading.Tasks.Task<System.Nullable<long>> CreateAsync(ArticlesClient.ArticlesService.ArticleData article);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticlesService/Update", ReplyAction="http://tempuri.org/IArticlesService/UpdateResponse")]
        void Update(ArticlesClient.ArticlesService.ArticleData article);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticlesService/Update", ReplyAction="http://tempuri.org/IArticlesService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(ArticlesClient.ArticlesService.ArticleData article);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticlesService/Delete", ReplyAction="http://tempuri.org/IArticlesService/DeleteResponse")]
        void Delete(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticlesService/Delete", ReplyAction="http://tempuri.org/IArticlesService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(long id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IArticlesServiceChannel : ArticlesClient.ArticlesService.IArticlesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ArticlesServiceClient : System.ServiceModel.ClientBase<ArticlesClient.ArticlesService.IArticlesService>, ArticlesClient.ArticlesService.IArticlesService {
        
        public ArticlesServiceClient() {
        }
        
        public ArticlesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ArticlesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArticlesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArticlesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ArticlesClient.ArticlesService.ArticleData[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<ArticlesClient.ArticlesService.ArticleData[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public ArticlesClient.ArticlesService.ArticleData Get(long id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<ArticlesClient.ArticlesService.ArticleData> GetAsync(long id) {
            return base.Channel.GetAsync(id);
        }
        
        public System.Nullable<long> Create(ArticlesClient.ArticlesService.ArticleData article) {
            return base.Channel.Create(article);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<long>> CreateAsync(ArticlesClient.ArticlesService.ArticleData article) {
            return base.Channel.CreateAsync(article);
        }
        
        public void Update(ArticlesClient.ArticlesService.ArticleData article) {
            base.Channel.Update(article);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(ArticlesClient.ArticlesService.ArticleData article) {
            return base.Channel.UpdateAsync(article);
        }
        
        public void Delete(long id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(long id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
